# Generated by Django 2.1.4 on 2018-12-10 08:01

from django.db import migrations, models
import django.db.models.deletion
import staticpages.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=staticpages.models.filename)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL to file')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(max_length=20, null=True, verbose_name='Категория страницы'),
        ),
        migrations.AddField(
            model_name='file',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpages.Page', verbose_name='Страница документов'),
        ),
    ]
