# Generated by Django 2.1.4 on 2018-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0004_auto_20181210_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
    ]
