# Generated by Django 2.1.4 on 2018-12-06 06:45

import departments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, upload_to=departments.models.image_folder, verbose_name='Картинка отдела'),
        ),
    ]
