# Generated by Django 2.1.4 on 2018-12-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название эталона')),
                ('slug', models.SlugField(blank=True, verbose_name='Ссылка на эталон')),
                ('text', models.TextField(verbose_name='Описание эталона')),
            ],
            options={
                'verbose_name': 'Эталон',
                'verbose_name_plural': 'Эталоны',
            },
        ),
        migrations.CreateModel(
            name='Standarts_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тип эталона')),
                ('slug', models.SlugField(blank=True, verbose_name='Ссылка на тип эталона')),
            ],
            options={
                'verbose_name': 'Тип эталона',
                'verbose_name_plural': 'Типы эталонов',
            },
        ),
        migrations.AddField(
            model_name='standard',
            name='standards_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standards.Standarts_Type', verbose_name='Тип эталона'),
        ),
    ]
